# Guard Rails
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml" ]
        additional_dependencies: [ "bandit[toml]" ]

# Formatters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
#        language_version: python3.9
        args:
          - --line-length=128
      - id: black-jupyter
#        language_version: python3.9
        args:
          - --line-length=128
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

# Code Checkers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-docstring-first
      - id: debug-statements
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=128"
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy

# Code Correctors
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.7.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies: &flake8_deps
          - flake8-bugbear==22.8.23
          - flake8-comprehensions==3.10.0
          - flake8-docstrings==1.6.0
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
an        args: [--all]

# Git Helpers
#  - repo: https://github.com/commitizen-tools/commitizen
#      rev: v2.35.0
#      hooks:
#        - id: commitizen
#        - id: commitizen-branch
#          stages: [push]
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#      rev: v4.3.0
#      hooks:
#        - id: check-merge-conflict
#        - id: no-commit-to-branch
